
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - image: docker.io/prashkotam/vote:b128a43290ab1d7a4a94cd3715f727fb65764fe0
        name: vote-ui
        ports:
        - containerPort: 80
